### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by NineFingersj** [cxdy/pybomber#2]
When I try to use the script, I spite of the fact that I have the accounts to file in the same directory as the script, it still says the accounts txt file isn't found. Could someone please tell me what I'm doing wrong?

**Comment by cxdy** [comment]
Hey, that feature isn't supported by the original script but there is a
fork that you might be referring to.

Feel free to submit an issue over there. (assuming @saatanaperkele has it
turned on)

https://github.com/saatanaperkele/pybomber

**Comment by saatanaperkele** [comment]
Hey @NineFingersj, what arguments are you using with the script? Can I also get a copy of the format of accounts.txt? (you may censor as needed).

**Comment by saatanaperkele** [comment]
And also, to keep from blowing up @cxdy's notifs, please make an issue on my fork. 

Thanks,
jukka
