### ISSUE TITLE
smtp.connect() error

### ISSUE THREAD

**Issue by sarthak1598** [cxdy/pybomber#3]
As while running the code , 
always the smtp connection error arises while making the tls connection with for eg gmail smtp server and port number 587 

i  also tried to change the smtp port to 25 and 465 but nothing happened ...
Dont know why this error is arising :

smtplib.SMTPConnectError: (421, 'Cannot connect to SMTP server 74.125.24.108 (74.125.24.108:587), connect error 10060')

**Comment by cxdy** [comment]
Have you tried making an app password within your Google account settings?

Cody Kaczynski
www.CodyKaczynski.com

**Comment by martintc** [comment]
This is what is being talked about. You need to go into your google setting and toggle this setting. Then this application works. 

<img width="1280" alt="Screen Shot 2020-12-20 at 4 38 35 AM" src="https://user-images.githubusercontent.com/33560895/102713482-6a7f3980-427d-11eb-9648-0bd802cbd935.png">
